CREATE TABLE atenciones_urgencia (
    id BIGINT GENERATED ALWAYS AS IDENTITY,
    fecha DATE NOT NULL,
    anio INT NOT NULL,
    semana INT,
    id_establecimiento VARCHAR(50),
    nombre_establecimiento VARCHAR(200),
    tipo_establecimiento VARCHAR(100),
    tipo_atencion VARCHAR(100),
    tipo_campana VARCHAR(100),
    codigo_region INT,
    nombre_region VARCHAR(100),
    codigo_dependencia INT,
    nombre_dependencia VARCHAR(150),
    codigo_comuna INT,
    nombre_comuna VARCHAR(100),
    id_causa INT,
    glosa_causa VARCHAR(200),
    total_atenciones INT,
    menores_1 INT,
    de_1_a_4 INT,
    de_5_a_14 INT,
    de_15_a_64 INT,
    de_65_y_mas INT,
    PRIMARY KEY (id, anio)
) PARTITION BY RANGE (anio);